# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dba7624bdad3ee73b73dafa734bca6498103b6fc44b40d3cd4e74e627e3b15dcce21e335ceffc477de8542869cdd7eda74175b5526c91c7668b5aba8514bb18e

test:
  secret_key_base: ae5ba668f9b877cf1fbd0d1a9818dc9149bd973e7245d332239a4769ca112bce65bf20cad3b368b903c00d463ddd28ad676bafe0a8568608b8a82a3e24eac655

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
